version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mysql:5.7
        command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --log-bin=on --server_id=111
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true

    working_directory: /go/src/github.com/hanchuanchuan/goInception

    steps:
      - run:
          name: "Make Release"
          command: make release

  publish-github-release:
    environment:
      ARTIFACTS: /go/src/github.com/hanchuanchuan/goInception/release
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: /go/src/github.com/hanchuanchuan/goInception/release
    - run:
        name: "Publish Release on GitHub"
        command: |
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r goInceptionTest -c ${CIRCLE_SHA1} ${CIRCLE_TAG} $ARTIFACTS


workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^[Vv]\d+\.\d+\.\d+$/
