version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    branches:
      ignore: gh-pages

    docker:
      - image: circleci/golang:1.12
      - image: cibuilds/github:0.10
      - image: circleci/mysql:5.7
        command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --log-bin=on --server_id=111
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true

    working_directory: /go/src/github.com/hanchuanchuan/test

    steps:
      - checkout
      - run: rm -f go.sum

      - run:
          name: "Make Release"
          command: make release

      - run:
          name: "ls"
          command: ls -l release


      - run:
          name: Publish Release on GitHub
          command: |
            GIT_COMMIT_DESC=$(git log --format=oneline -n 1 ${CIRCLE_SHA1} | sed -E 's/^[^ ]+ (.*)$/\1/g')
            echo 'commit message:' "$GIT_COMMIT_DESC"

            if [[ "$GIT_COMMIT_DESC" =~ ^[vV][0123456789]+\.[0123456789]+.* ]] || [[ "$GIT_COMMIT_DESC" == ^[mM]erge* ]]; then
                echo "Publish Release on GitHub"


                CIRCLE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

                if [ -n "${CIRCLE_TAG}" ]; then
                  go get github.com/tcnksm/ghr
                  ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -delete -replace -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./release
                else
                  echo '无效$CIRCLE_TAG！'
                fi
            else
              echo "不符合发版格式，跳过Release！！！"
            fi


# git log -1 --pretty=%B ${CIRCLE_SHA1}
# git log --format=oneline -n 1 ${CIRCLE_SHA1}
# export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 | sed -E 's/^[^ ]+ (.*)$/\1/g')

  # publish-github-release:
  #   environment:
  #     ARTIFACTS: /go/src/github.com/hanchuanchuan/test/release
  #   docker:
  #   - image: cibuilds/github:0.10
  #   steps:
  #   - attach_workspace:
  #       at: /go/src/github.com/hanchuanchuan/test/release
  #   - run: ls -l
  #   - run: pwd
  #   - run: ls -l /go/src/github.com/hanchuanchuan/goInception/
  #   - run: ls -l /go/src/github.com/hanchuanchuan/goInception/release
  #   - run:
  #       name: "Publish Release on GitHub"
  #       command: |
  #         go get github.com/tcnksm/ghr
  #         ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r test -c ${CIRCLE_SHA1} ${CIRCLE_TAG} $ARTIFACTS
